name: CI/CD Laravel + Nginx + MySQL to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout repository
      uses: actions/checkout@v3
      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and push Laravel image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/evento:v4

 
    - name: Create SSH key file
      run: |
        echo "${{ secrets.VM_SSH_KEY }}" > github_actions_key
        chmod 600 github_actions_key

    - name: Deploy to Minikube
      run: |
        ssh -o StrictHostKeyChecking=no -i github_actions_key vboxuser@192.168.43.146 "
          kubectl config use-context test-cluster &&
          eval \$(minikube -p test-cluster docker-env) &&
          kubectl apply -f k8s/namespace.yaml &&
          kubectl apply -f k8s/mysql-secret.yaml &&
          kubectl apply -f k8s/mysql-pvc.yaml &&
          kubectl apply -f k8s/mysql-deployment.yaml &&
          kubectl apply -f k8s/laravel-pvc.yaml &&
          kubectl apply -f k8s/laravel-deployment.yaml &&
          kubectl apply -f k8s/nginx-pvc.yaml &&
          kubectl apply -f k8s/nginx-deployment.yaml &&
          kubectl rollout status deployment/mysql &&
          kubectl rollout status deployment/laravel &&
          kubectl rollout status deployment/nginx
        "
