name: CI/CD Laravel + Nginx + MySQL to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Laravel image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/evento:v4

    - name: Deploy to Minikube
      run: |
        kubectl config use-context test-cluster
        # Use Minikube's Docker daemon
        eval $(minikube -p test-cluster docker-env)

        # Apply MySQL PVC and Deployment
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/mysql-secret.yaml
        kubectl apply -f k8s/mysql-pvc.yaml
        kubectl apply -f k8s/mysql-deployment.yaml

        # Apply Laravel Deployment
        kubectl apply -f k8s/laravel-pvc.yaml 
        kubectl apply -f k8s/laravel-deployment.yaml

        # Apply Nginx PVC and Deployment
        kubectl apply -f k8s/nginx-pvc.yaml
        kubectl apply -f k8s/nginx-deployment.yaml

        # Wait for pods to be ready
        kubectl rollout status deployment/mysql
        kubectl rollout status deployment/laravel
        kubectl rollout status deployment/nginx
